language: python

matrix:
    include:
        - python: 2.7
          os: linux
          dist: trusty
          env: TOXENV=py27
        - python: pypy
          os: linux
          dist: trusty
          env: TOXENV=pypy
        - python: 3.5
          os: linux
          dist: trusty
          env: TOXENV=py35
        - python: 3.6
          os: linux
          dist: trusty
          env: TOXENV=py36
        - python: 3.7
          os: linux
          dist: xenial
          env: TOXENV=py37
        - python: 3.8
          os: linux
          dist: xenial
          env: TOXENV=py38

# command to install dependencies
install:
  - "pip install ."

# command to run tests
script: nosetests
